TS3 (creating UserInfo class) + TS7 (making a command to populate default members in the db) changes.
markkyaw/trojan_scheduler pull request #4
Opened 2022-02-18 06:43 UTC by jleodones

2022-02-18 06:45 UTC, jleodones commented
![](https://github.trello.services/images/mini-trello-icon.png) [TS-3: Create a User model to store users](https://trello.com/c/xVGe82Ar/3-ts-3-create-a-user-model-to-store-users)

2022-02-18 06:45 UTC, jleodones commented
![](https://github.trello.services/images/mini-trello-icon.png) [TS-7: Create management commands that populates basicclassinfo, basicclasssection, instructor](https://trello.com/c/dPZDGwXD/7-ts-7-create-management-commands-that-populates-basicclassinfo-basicclasssection-instructor)

2022-02-20 18:22 UTC, markkyaw requested changes
And try running 
`python3 manage.py populate_default` and try to debug the errors :D

2022-02-20 18:22 UTC, markkyaw commented on apps/users/models.py
> +    user = models.OneToOneField(User)
add `related_name="info"` and `on_delete=models.CASCADE`

2022-02-20 18:22 UTC, markkyaw commented on apps/classes/models.py
> +    class_info = models.ForeignKey(BasicClassInfo)
add `related_name="class_section"` and `on_delete=models.CASCADE`

2022-02-20 18:22 UTC, markkyaw commented on apps/classes/management/commands/populate_default.py
> +            User.objects.create_user(user, user + "@gmail.com", user + "pw")
Put this in a try catch block
```
try:
  # check if user exists by getting user object based on username/email
except:
  # create new user object
```

2022-02-20 18:22 UTC, markkyaw commented on apps/classes/management/commands/populate_default.py
> +        for key, value in instructors_list:
iterate using `instructors_list.items()`

2022-02-20 18:22 UTC, markkyaw commented on apps/classes/management/commands/populate_default.py
> +            value = Instructor.objects.create(name=key)
i realized can't update dict like that lmfao
`instructors_list[key] = ...`

And do `update_or_create` <- so we don't create duplicate objects when we run this multiple times

2022-02-20 18:22 UTC, markkyaw commented on apps/classes/management/commands/populate_default.py
> +            "itp_380": BasicClassInfo.objects.create(
`update_or_create` for all of them in here

2022-02-20 18:22 UTC, markkyaw commented on apps/classes/management/commands/populate_default.py
> +            "itp380_lecture": BasicClassSection.objects.create(
`update_or_create`

2022-02-21 02:13 UTC, markkyaw commented on apps/classes/management/commands/populate_default.py
> +            value = Instructor.objects.create(name=key)
Doc: https://docs.djangoproject.com/en/4.0/ref/models/querysets/#update-or-create
It returns a tuple so look at what we need to save

2022-03-20 20:07 UTC, markkyaw submitted a review, later dismissed

2022-03-20 20:10 UTC, markkyaw approved these changes

2022-03-20 20:10 UTC, merged