Started the views in views.py
markkyaw/trojan_scheduler pull request #6
Opened 2022-02-26 20:42 UTC by aliceyzhou

I'm not sure how to make it so it searches through all the objects, currently it only checks if the object passed to it matches the criteria.

2022-03-09 04:34 UTC, markkyaw requested changes

2022-03-09 04:34 UTC, markkyaw commented on trojanscheduler/views.py
> +            return object.class_code + " " + object.class_section
Sorry for the late feedback. Refer to https://github.com/markkyaw/trojan_scheduler/blob/main/api/v1/classes/views/views.py to get an idea on how `view` files should be formatted.
Basically, you'll need to create corresponding `urls.py` as shown in https://github.com/markkyaw/trojan_scheduler/blob/main/api/v1/classes/urls.py
Create a new `url` and call it like `class_search` or something. And the view file will look like the class based view listed here
https://www.django-rest-framework.org/tutorial/3-class-based-views/
Let me know if you wanna pair program on this :)

2022-03-09 04:36 UTC, markkyaw commented
Also, add `.DS_Store` to your `.gitignore` file since these are files auto created by macs and we don't need them :)

2022-03-09 04:36 UTC, markkyaw commented on trojanscheduler/views.py
> +            return object.class_code + " " + object.class_section
To make it search, you'll be doing
`BasicClassSection.objects.filter`
You can read more about them here
https://docs.djangoproject.com/en/4.0/topics/db/queries/

2022-03-24 04:13 UTC, aliceyzhou commented
Read the page on querying, edited the view to call filter() and order_by(). Also added the two functions to urls. Overall, I'm not

2022-03-25 22:58 UTC, markkyaw commented
![](https://github.trello.services/images/mini-trello-icon.png) [TS-8: Create Views that will return stuff](https://trello.com/c/CeUrWfn9/8-ts-8-create-views-that-will-return-stuff)

2022-03-25 23:30 UTC, markkyaw approved these changes

2022-03-25 23:30 UTC, merged